In [28]:
import numpy as np
import pandas as pd

### Creating a DataFrame

In [29]:
data = {
    'Name': ['John','Anna','Peter','Linda'],
    'Age': [28,34,29,42],
    'City': ['New York','Paris','Berlin','London'],
    'Salary': [65000,70000,62000,85000]
}
Data_Frame = pd.DataFrame(data)
print(Data_Frame)

    Name  Age      City  Salary
0   John   28  New York   65000
1   Anna   34     Paris   70000
2  Peter   29    Berlin   62000
3  Linda   42    London   85000

In [30]:
data_list= [
    ['John', 28,'New York',65000],
    ['Anna',34,'Paris',70000],
    ['Peter',29,'Berlin',62000],
    ['Linda',42,'London',85000]
]

data_list1 = pd.DataFrame(data_list)
columns = ['Name', 'Age','City','Salary']
df2 = pd.DataFrame(data_list,columns=columns)
print(df2)

    Name  Age      City  Salary
0   John   28  New York   65000
1   Anna   34     Paris   70000
2  Peter   29    Berlin   62000
3  Linda   42    London   85000

### Selecting and Indexing of Columns

In [31]:
df2[['Name','City']]

    Name      City
0   John  New York
1   Anna     Paris
2  Peter    Berlin
3  Linda    London

In [32]:
df2[['Name','Age','City']]

    Name  Age      City
0   John   28  New York
1   Anna   34     Paris
2  Peter   29    Berlin
3  Linda   42    London

In [33]:
print(df2)

    Name  Age      City  Salary
0   John   28  New York   65000
1   Anna   34     Paris   70000
2  Peter   29    Berlin   62000
3  Linda   42    London   85000

In [34]:
df2['Name']

0     John
1     Anna
2    Peter
3    Linda
Name: Name, dtype: str

### Creating a new Column

In [35]:
df2["Designation"] =["Lawyer" ,"Servant","Engineer","Police"]

In [36]:
df2

    Name  Age      City  Salary Designation
0   John   28  New York   65000      Lawyer
1   Anna   34     Paris   70000     Servant
2  Peter   29    Berlin   62000    Engineer
3  Linda   42    London   85000      Police

In [39]:
df2.drop('Designation',axis = 1,inplace=True)

In [40]:
df2

    Name  Age      City  Salary
0   John   28  New York   65000
1   Anna   34     Paris   70000
2  Peter   29    Berlin   62000
3  Linda   42    London   85000

In [42]:
df2.drop(["City","Salary"],axis = 1)

    Name  Age
0   John   28
1   Anna   34
2  Peter   29
3  Linda   42

In [43]:
df2

    Name  Age      City  Salary
0   John   28  New York   65000
1   Anna   34     Paris   70000
2  Peter   29    Berlin   62000
3  Linda   42    London   85000

In [44]:
df2.drop(0,axis = 0)

    Name  Age    City  Salary
1   Anna   34   Paris   70000
2  Peter   29  Berlin   62000
3  Linda   42  London   85000

### Selecting Row

In [ ]:
df2.loc[0] #location

Name          John
Age             28
City      New York
Salary       65000
Name: 0, dtype: object

In [46]:
df2.iloc[3] #IndexLocation

Name       Linda
Age           42
City      London
Salary     85000
Name: 3, dtype: object

In [ ]:
### Selecting Subset of Row and Columns

In [55]:
df2.loc[0:1][["City","Salary"]]

       City  Salary
0  New York   65000
1     Paris   70000

In [56]:
df2.loc[2:3][["Name","Age"]]

    Name  Age
2  Peter   29
3  Linda   42

### Conditional Selection

In [62]:
df2

    Name  Age      City  Salary
0   John   28  New York   65000
1   Anna   34     Paris   70000
2  Peter   29    Berlin   62000
3  Linda   42    London   85000

In [63]:
#Only want to see those people whose age is above 30

In [64]:
df2[df2["Age"]>30]

    Name  Age    City  Salary
1   Anna   34   Paris   70000
3  Linda   42  London   85000

In [67]:
df2[(df2["Age"]>30) & (df2["City"] == "Paris")]

   Name  Age   City  Salary
1  Anna   34  Paris   70000